using visitorPattern;
CarClass pickup = new CarBuilder(new DieselPickup()).CreateCar();
CarClass sedan = new CarBuilder(new ElectricSedan()).CreateCar();
ConcreteVisitor visitor = new();

Console.WriteLine("Truck:");
Console.WriteLine("---------------");
Console.WriteLine(pickup.ToString());
Console.WriteLine("---------------");
visitor.Visits(pickup);
Console.WriteLine($"Max Range: {visitor.Range} miles");
Console.WriteLine($"0 to 60 time: {visitor.TimeTo60} seconds");
Console.WriteLine($"Load Capacity: {visitor.LoadCapacity} kg");
Console.WriteLine("===========================================");
Console.WriteLine("Sedan:");
Console.WriteLine("---------------");
Console.WriteLine(sedan.ToString());
Console.WriteLine("---------------");
visitor.Visits(sedan);
Console.WriteLine($"Max Range: {visitor.Range} miles");
Console.WriteLine($"0 to 60 time: {visitor.TimeTo60} seconds");
Console.WriteLine($"Load Capacity: {visitor.LoadCapacity} kg");
